#134 信号機解体
hibiya-itchief/quaint-app pull request #157
Opened 2023-06-10 13:01 UTC by hibiyahibiyahibiya

存在する公演が0426spectestと11rしかない？ため
その２公演でのみ正しく動作していることを確認しました
また例により競合してしまうため１回branchをつくってぷるりくします
↑まったく同じ内容であれば自分でまーじしてもいいですか？

2023-06-10 15:04 UTC, ekkekuru2 requested changes
今日だけで3件もissueに取り組んでてすごい！以上3点修正をお願いします。
競合は起きてなさそうだから大丈夫！
それからあれだね、あなたにAPI経由で公演を追加したりできる権限を付けたほうがよいね

2023-06-10 15:04 UTC, ekkekuru2 commented on pages/groups/_groupId/index.vue
> +
この発想はすごく良いと思う。
ただ、APIの仕様とあっていない((省略)/stock,(省略)/taken_ticketsというエンドポイントは無い(作ってもよいけど))ので、以下を参照してエンドポイントを正しくたたけばOK!!
https://quaint-api.azurewebsites.net/docs#/tickets/count_tickets_groups__group_id__events__event_id__tickets_get

2023-07-04 07:18 UTC, hibiyahibiyahibiya commented
ついにできました！！！！！！
各公演のtaken_ticketsをいじるのが面倒なのでそこは試していないのですが、console.logを見る限りちゃんと動作してるのでぷるりくします
と言いたいのですが、mainとdevelopどちらにぷるりくすればよいんですかね…？
とりあえずここにコメントという形で報告しておきます
また、createLike()とdeleteLike()をいまコメントアウトの中に入れてます。
復活させることはあるのですかね…？？個人的にはあまり必要性を感じていないのですが…

2023-07-04 09:29 UTC, ekkekuru2 commented
おつかれさま！複数のアカウントで試した感じ残席状況の表示は黄色・赤色ともにばっちり
![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/c4725146-7ce9-4148-8428-5e527da8b451)
![image](https://github.com/hibiya-itchief/quaint-app/assets/71656810/17748514-6725-4be3-b95d-a5e816af19e3)

2023-07-04 09:33 UTC, ekkekuru2 commented
プルリク先はdevelopで良いよ。開発中はdevelopにコミットしていって一通り完成したらmainにマージしてリリースする感じで
それから、createLike()とdeleteLike()の扱いについては、もう使わないコードをコメントで残すのはあんまり良くない(復活させたくなったら後からGitの履歴をたどることができる)から削除してもいいかも

2023-07-04 09:39 UTC, ekkekuru2 commented
発見してしまったバグが3つあって
1つ目は複数個公演があるときに、どの公演をクリックしても、一番最後の公演を取得するダイアログが表示される

https://github.com/hibiya-itchief/quaint-app/assets/71656810/70b7656a-9af5-4fca-a7f3-ee057b8c2ce9

2つ目は、整理券をキャンセルしようとすると、同じくどの整理券をキャンセルしようとしても一番下の整理券をキャンセルするダイアログが表示される上に、Cannot read properties of undefined (reading of 'id')というエラーが出る

https://github.com/hibiya-itchief/quaint-app/assets/71656810/399fe00d-b7f8-454e-9ba7-d4cec5a8da9a

3つ目は、残り2席の公演で、3席取ろうとするとエラーで弾かれて、その後2席でとろうとするとフリーズする。わけが分からない

https://github.com/hibiya-itchief/quaint-app/assets/71656810/1442a165-eb78-4a7e-90f9-179a6b4ca555

2023-07-04 09:41 UTC, ekkekuru2 commented
1と2については、v-forのv-keyあたりが原因なんじゃないかと思う
(参考) https://note.com/shift_tech/n/nbcae6c4ab442
3は全くわからん怖い

これらのバグが @hibiyahibiyahibiya の変更によって起こったのかはまだわからないから調査してみよう。どのコミットからバグるようになってしまったのか

2023-07-04 10:09 UTC, ekkekuru2 commented
今Gitのログをさかのぼってたら、1,2については4月時点からあったっぽいな怖すぎ

2023-07-04 10:12 UTC, hibiyahibiyahibiya commented
おそろしいですね………
信号機から内容が変わるので、issueを改めてつくってもよいですか？
それか、まったく同じ動画・文章でissue立てていただいてもよいでしょうか

2023-07-04 10:16 UTC, ekkekuru2 commented
そうねissue立ててもらってもいい？

2023-07-04 10:17 UTC, ekkekuru2 commented
それからいったんこの信号機解体のPRはマージしちゃおうか

2023-07-04 10:17 UTC, ekkekuru2 approved these changes

2023-07-04 10:18 UTC, merged