信号機の正常動作&バグの修正
hibiya-itchief/quaint-app pull request #182
Opened 2023-07-05 12:17 UTC by ekkekuru2

#157 および #177 のリリース(?)

2023-07-05 13:38 UTC, hibiyahibiyahibiya requested changes
Review in codespaceしてみたんですが、
最初はスライダーで予約する席数を指定できていたのに、
生徒ログインボタンを押す→エラーがでる→戻る
をしたら画像のようにスライダーが消えました
![Screenshot 2023-07-05 at 22-29-11 星陵祭](https://github.com/hibiya-itchief/quaint-app/assets/128669695/ec0b56c8-5cc4-413d-bffc-3a4401a503f3)
これはもしかしてログインしている判定になったゆえの仕様、とかだったりしますか？

あと、たくさんのvueが更新されているのは前述のlintなる作業によるものという認識であってますかね？

前々から思っていましたが、ぷるりくのreview側って大変ですよね…
ミスを見つけるコツとかってありますか？？

2023-07-05 13:38 UTC, hibiyahibiyahibiya commented on pages/groups/_groupId/index.vue
> +*/
初reviewで機能の使い方がよくわからないのですが
とりあえず、ここのコメントアウトは消していただきたいです

2023-07-05 13:38 UTC, hibiyahibiyahibiya commented on pages/groups/_groupId/index.vue
> +    以下、かつて存在した「いいね機能」の跡を遺しておく
ここから始まるコメントアウトもよろしくお願いします
拒否事由はなんにせよこれでreviewとしては成り立つのではないでしょうか

2023-07-05 13:44 UTC, ekkekuru2 commented
> これはもしかしてログインしている判定になったゆえの仕様、とかだったりしますか？

生徒ログインになると1席しか指定できないようになるからこの挙動であってるはず。エラーがちょっとわかんないけど

そういえば今のところ保護者アカウントはこっちで作って配布って話にチーフとなってるじゃん？こっちで作って配布するアカウントは生徒ログインと同じ扱いになっちゃうから1席までしか現状予約できないのを直さないと

2023-07-05 13:45 UTC, ekkekuru2 commented
> あと、たくさんのvueが更新されているのは前述のlintなる作業によるものという認識であってますかね？

です！飲み込みがはやい！！！

2023-07-05 13:50 UTC, ekkekuru2 commented on pages/groups/_groupId/index.vue
> +    以下、かつて存在した「いいね機能」の跡を遺しておく
めっちゃしっかりレビューしてくれてありがとう！！

2023-07-05 13:51 UTC, ekkekuru2 commented
コメントアウトの削除を行いました

2023-07-05 13:52 UTC, ekkekuru2 commented
もしよろしければお手空きの時間に再度レビューしていただき、もし問題点なければApprovください～

2023-07-05 13:56 UTC, ekkekuru2 commented
> 前々から思っていましたが、ぷるりくのreview側って大変ですよね…
> ミスを見つけるコツとかってありますか？？

分かるむずい
コツ、、、別に僕も超初心者なんで良いこと言えないけど、コーナーケース(境目になる条件を入れて挙動があってるかどうか)を試すのは良いかも。世の中のOSSれびゅわーはどうしてるんだろう
あと実は本来は人の目だけのチェックに頼らないようにヨースコードを書くと同時にソースコードのテストってのも書くべきなんだよね...

2023-07-05 14:12 UTC, hibiyahibiyahibiya commented
保護者アカウントについてどこまで決まったのか覚えていないですが、
たぶん保護者アカウントであることを検知する仕組みはありますよね？

ソースコードと同時にソースコードのテストを書くってどういうことですか？詳しく教えていただきたいです

明日には再度れびゅーします、お待ちください

2023-07-06 02:19 UTC, hibiyahibiyahibiya reviewed
すみません、Review in codespaceで確認しようと思ったのですが、/groupsに入れません（エラーコード502）
ぷるりく内容と関係ないのですが、直していただきたいです
![image](https://github.com/hibiya-itchief/quaint-app/assets/128669695/d52245d3-65f4-4920-8d9a-864a543d1f4c)

2023-07-11 15:58 UTC, hibiyahibiyahibiya approved these changes
細かい調整はまたするとして
これらの変更よいのではないでしょうか！！！
approveしちゃいます

2023-07-11 16:25 UTC, ekkekuru2 reviewed
🚀

2023-07-11 16:25 UTC, merged