#212-アカウントのowner表示
hibiya-itchief/quaint-app pull request #216
Opened 2023-07-15 09:13 UTC by hibiyahibiyahibiya

#212 参照

2023-07-15 12:44 UTC, ekkekuru2 requested changes

2023-07-15 12:44 UTC, ekkekuru2 commented on layouts/default.vue
> +                  v-show="$auth.user?.groups?.includes(userGroups.owner)"
userGroups.adminは164行目で環境変数から代入して作ってます。
現状だと、userGroups.ownerは宣言されて無いですね

2023-07-15 13:33 UTC, hibiyahibiyahibiya commented on layouts/default.vue
> +                  v-show="$auth.user?.groups?.includes(userGroups.owner)"
あ、そこでadmin指定してたんですね
164行目あたりにownerバージョンをつくればいいんですかね？

2023-07-15 17:49 UTC, hibiyahibiyahibiya commented on layouts/default.vue
> +                  v-show="$auth.user?.groups?.includes(userGroups.owner)"
とりあえず同様に追加してみました！

2023-07-16 00:45 UTC, ekkekuru2 commented on layouts/default.vue
> +                  v-show="$auth.user?.groups?.includes(userGroups.owner)"
結果的にはそれで合ってます！推察力👍です

Process.env.~~ が
どこで定義されてるかわかった方がいいと思うので、書いておきます。

https://github.com/hibiya-itchief/quaint-app/blob/main/env.production.js

env.(各環境).js の最後の行で定義されてます
代入されてる文字列は、Azure ADでグループのプロパティを見た時に出てくるuuidというidです。

それぞれの環境で違う値を読み込む処理とかはnuxt.config.tsに書いてあるのでぜひ読んでみてください

2023-07-16 00:51 UTC, ekkekuru2 approved these changes
issueを立ててから解決するまでがどんどん早くなっててすごい！！！

2023-07-16 00:53 UTC, ekkekuru2 requested changes
待ってごめん、なんかlintエラーが出てるなそこだけ変更お願いします

2023-07-16 05:17 UTC, hibiyahibiyahibiya commented
これでどうですか！！！

2023-07-16 14:54 UTC, ekkekuru2 approved these changes
おつかれさまです！！ありがとう

2023-07-16 14:54 UTC, merged