/groups デフォルト順のソートはnuxt generateで
hibiya-itchief/quaint-app pull request #332
Opened 2023-08-25 16:16 UTC by ekkekuru2

/groups デフォルト順のソートはnuxt generateでするようにした
- #331 

@hibiyahibiyahibiya 作った人が一番わかると思うのでレビューお願いします

2023-08-25 16:18 UTC, ekkekuru2 commented on pages/groups/index.vue
> +      this.$route.query.s === 'id'
クエリパラメータがついてる時のみ、っていう意図の条件分岐なのだけど、
そういえば?s=id となることってないよね手動で設定しない限り
別にあっても問題はないのだけど、どうしたらいい？

2023-08-26 04:04 UTC, hibiyahibiyahibiya commented on pages/groups/index.vue
> +      this.$route.query.s === 'id'
s=idの場合は書かなくていいと思います
groupnameかtitleじゃなければ必ずデフォルト順になる設計で

2023-08-26 12:30 UTC, hibiyahibiyahibiya requested changes

2023-08-26 12:30 UTC, hibiyahibiyahibiya commented on pages/groups/index.vue
> +      this.$route.query.s === 'id'
s=idを消すのと、この先264行目のelse→デフォルト順、は不要なんじゃないかと思うのですがどうでしょう
それ以外はおけです

2023-08-26 13:00 UTC, ekkekuru2 commented on pages/groups/index.vue
> +      this.$route.query.s === 'id'
了解

2023-08-26 13:00 UTC, ekkekuru2 commented
@hibiyahibiyahibiya 変更しました～

2023-08-26 13:08 UTC, hibiyahibiyahibiya approved these changes

2023-08-26 14:23 UTC, merged