/system チーフ会作成の文章に
hibiya-itchief/quaint-app pull request #437
Opened 2023-09-10 09:40 UTC by hibiyahibiyahibiya

誤字などは訂正。
本当は保護者優先券の画像などを載せるべきなのだろうが、構図が思いつかず、とりあえずPR。

2023-09-10 15:33 UTC, ekkekuru2 requested changes
/login にある紙整理券の情報と似たような情報がありつつも、その二つがばらばらのものとして存在してるから混乱すると思う。
かといって、/loginから/systemにリンクを貼るだけじゃない方がいいと思う。現状の/loginからリンクを踏まずとも紙整理券の情報が分かる点は良いから
デザインや載ってる情報の記載の仕方、文言の表記等で両者の一貫性を作りたい
ごめんこんなめんどくさいこと言って。けどこれで公開しちゃうと混乱しちゃうと思うからいったんRequest changesで

2023-09-11 15:34 UTC, hibiyahibiyahibiya commented
調整いたしました。
![Screenshot 2023-09-12 at 00-14-25 日比谷高校星陵祭2023公式サイト](https://github.com/hibiya-itchief/quaint-app/assets/128669695/fdc6afe9-d8ba-47f7-a2fa-423f1fdb0944)
（/loginから剽窃した後整えた文章が追加されるなど）

![Screenshot 2023-09-12 at 00-13-47 日比谷高校星陵祭2023公式サイト](https://github.com/hibiya-itchief/quaint-app/assets/128669695/297d55a6-455c-4355-9817-7aaddeb83e5b)
（この写真、下の画像群が読み込めてませんね）

![Screenshot 2023-09-12 at 00-13-39 日比谷高校星陵祭2023公式サイト](https://github.com/hibiya-itchief/quaint-app/assets/128669695/922e4a42-1fcf-4bda-941a-cce58db30de9)

requested reviewの部分以外にも少し微調整を加えました。

2023-09-11 16:02 UTC, ekkekuru2 submitted a review, later dismissed
めっちゃいいと思う。Approve！
細かいとこだけ修正してからマージお願いします

2023-09-11 16:02 UTC, ekkekuru2 commented on pages/system.vue
> +              【注意点】<br />
ここ重要なポイントに蛍光マーカーor 破線みたいにできるとデザイン的に良いよね(やらなくてよい)

2023-09-11 16:02 UTC, ekkekuru2 commented on pages/index.vue
> +              「<ruby>祭徠<rt>さいらい</rt></ruby
ルビナイス

2023-09-11 16:02 UTC, ekkekuru2 commented on pages/login.vue
> +            <NuxtLink to="/schedule">配布スケジュール</NuxtLink
これくらいのゆるいリンクが良いのかもね。いいと思う

2023-09-11 16:10 UTC, hibiyahibiyahibiya commented on pages/system.vue
> +              3年生のクラス劇の整理券配布は、体育棟1階サブアリーナで行います。入口は1階アーケードです。<br />
うーん、項目２つですし、さらに、配布開始時間等の説明が長いために両項目が並列である印象を受けないので、そのままではどうでしょう

2023-09-11 16:22 UTC, ekkekuru2 commented
@hibiyahibiyahibiya 了解いいと思う！

2023-09-11 16:30 UTC, ekkekuru2 approved these changes

2023-09-11 16:30 UTC, merged